AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

#Globals:
#  Function:
#    Timeout: 160

Parameters:
  StageName:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "HelloWorld"
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /hello
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
            RouteSettings:
              ThrottlingBurstLimit: 600
  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_UM_CreateUser"
      Timeout: 30
      MemorySize: 10240
      CodeUri: CreateUser/
      Handler: index.handler
      Runtime: nodejs14.x
      Policies:
        - AmazonSESFullAccess
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Auth:
              Authorizer: "NONE"
            Method: "POST"
            Path: /user/createUser
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
  AuthenticateUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_UM_AuthenticateUser"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AuthenticateUser/
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        AuthenticateUser: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Auth:
              Authorizer: "NONE"
            Method: "POST"
            Path: /user/authenticateUser
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
  AuthenticateSocialUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_UM_AuthenticateSocialUser"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AuthenticateSocialUser/
      Handler: index.handler
      Runtime: nodejs14.x
      Policies:
        - AmazonSESFullAccess
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Auth:
              Authorizer: "NONE"
            Method: "POST"
            Path: /user/authenticateScUser
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
  Workspace:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_WM_Workspace"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AK_WM_Workspace/
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        CreateWorkspace: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /workspace/create
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
        WorkspaceMakeDefault:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /workspace/make-default
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
        GetWorkspace:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "GET"
            Path: /workspace/retrieve
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
        EditWorkspace:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "PUT"
            Path: /workspace/edit/{workspaceId}
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
        DeleteWorkspace:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "DELETE"
            Path: /workspace/delete/{workspaceId}
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
  Analytics:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_SM_Analytics"
      Timeout: 50
      MemorySize: 10240
      CodeUri: AK_SM_Analytics
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Auth:
              Authorizer: "NONE"
            Method: "POST"
            Path: /manageSM/analytics
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"            
  Member:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_UM_AddMember"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AK_UM_Member
      Handler: index.handler
      Runtime: nodejs14.x
      Policies:
        - AmazonSESFullAccess
      Events:
        AddMember: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /member/add-member
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
        RegisterMember: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Auth:
              Authorizer: "NONE"
            Method: "POST"
            Path: /member/reg-member
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
        RemoveMember: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "DELETE"
            Path: /member/delete/{workspaceId}/email/{email}
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
        GetMember: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "GET"
            Path: /member/retrieve/{workspaceId}
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
        EditMember: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "PUT"
            Path: /member/edit/{workspaceId}
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"            
  ListNotification:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_NF_ListNotification"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AK_NF_ListNotification/
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "GET"
            Path: /notification/list
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
  SaveUserPages:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_SM_saveUserPages"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AK_SM_saveUserPages/
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /manageSM/fb/saveUserPages
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"            
  CreatePost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_SM_createPost"
      Timeout: 50
      MemorySize: 10240
      CodeUri: AK_SM_createPost/
      Handler: index.handler
      Runtime: nodejs14.x
      Policies:
        - AmazonSESFullAccess
        - AmazonS3FullAccess
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /manageSM/postSocial
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
  Dashboard:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_SM_Dashboard"
      Timeout: 40
      MemorySize: 10240
      CodeUri: AK_SM_Dashboard/
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /manageSM/dashboard
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
  TwitterTrends:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_SM_Twitter_Trends"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AK_SM_Twitter_Trends/
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /cityTrends
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
  ContentManagement:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_CM_ContentManagement"
      Timeout: 40
      MemorySize: 10240
      CodeUri: AK_CM_ContentManagement/
      Handler: index.handler
      Runtime: nodejs14.x
      Policies:
        - AmazonS3FullAccess
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "GET"
            Path: /cm/uploadMedia
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
  DeleteMedia:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_CM_DeleteMedia"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AK_CM_DeleteMedia/
      Handler: index.handler
      Runtime: nodejs14.x
      Policies:
        - AmazonS3FullAccess
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /cm/removeMedia
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"              
  ListMedia:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_CM_ListMedia"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AK_CM_ListMedia/
      Handler: index.handler
      Runtime: nodejs14.x
      Policies:
        - AmazonS3FullAccess
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "GET"
            Path: /cm/retrieveMediaList
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"              
  MoveMedia:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_CM_MoveMedia"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AK_CM_MoveMedia/
      Handler: index.handler
      Runtime: nodejs14.x
      Policies:
        - AmazonS3FullAccess
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /cm/drag-media
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"              
  UploadFolder:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_CM_UploadFolder"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AK_CM_UploadFolder/
      Handler: index.handler
      Runtime: nodejs14.x
      Policies:
        - AmazonS3FullAccess
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /cm/createFolder
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"                        
  RetrieveAllSocialPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_SM_RetrieveAllSocialPost"
      Timeout: 50
      MemorySize: 10240
      CodeUri: AK_SM_RetrieveAllSocialPost/
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /manageSM/retrieveAllPost
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
  RetrievePostFromWeb:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_SM_RetrievePostFromWeb"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AK_SM_RetrievePostFromWeb/
      Handler: index.handler
      Environment:
        Variables:
          twitter_token: "AAAAAAAAAAAAAAAAAAAAABJRMAEAAAAAZCgIiNjUIBEmshoYJVkZsYV6Nc0%3DJtWFMmKy7Bz0CqFZI0xU9reKrJqYuHzpxW0fNgf9ptWDEskYRH"
      Runtime: nodejs14.x
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /manageSM/retrievePostWeb
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
  SocialMediaStatusUpdate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_SM_SocialMediaStatusUpdate"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AK_SM_SocialMediaStatusUpdate/
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: "POST"
            Path: /manageSM/socialMediaStatusUpdate
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
  LambdaAuth:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "LambdaAuth"
      Timeout: 30
      MemorySize: 10240
      CodeUri: LambdaAuth/
      Handler: index.handler
      Runtime: nodejs14.x            
  ActivateUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Dev_AK_UM_ActivateUser"
      Timeout: 30
      MemorySize: 10240
      CodeUri: AK_UM_ActivateUser/
      Handler: index.handler
      Runtime: nodejs14.x
      Policies:
        - AmazonSESFullAccess
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Auth:
              Authorizer: "NONE"
            Method: "GET"
            Path: /aikyne/confirmEmail
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"
        ExposeHeaders:
          - "*"
        MaxAge: 0
        AllowCredentials: true
      Tags:
        Tag: Value
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogs.Arn
        Format: $context.requestId
      # Auth:
      #   Authorizers:
      #     AK_Auth:
      #       JwtConfiguration:
      #         issuer: "https://aikyne1.eu.auth0.com/"
      #         audience:
      #           - https://storefriestest-jwt-authorizer
      #       IdentitySource: "$request.header.Authorization"
      #   DefaultAuthorizer: AK_Auth
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt LambdaAuth.Arn
            FunctionInvokeRole: !GetAtt LambdaAuth.Arn
            Identity:
              Headers:
                - Authorization
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: true
      DefaultRouteSettings:
        ThrottlingBurstLimit: 200
      RouteSettings:
        "POST /hello":
          ThrottlingBurstLimit: 500 # overridden in HttpApi Event
      StageVariables:
        mongoDB: "StorefriesQA1:vfRPJcXLcQyWEt2r@storefriesqa1.qpgagus.mongodb.net/Storefriesqa1"
        markettingMongoDB: "justin:cVMMTQazC5sAijai@socialmediacluster.yym8e.mongodb.net/marketting"
        authTokenURL: "https://aikyne1.eu.auth0.com/oauth/token"
        oauth_audience: "https://storefriestest-jwt-authorizer"
        oauth_issuer: "https://aikyne1.eu.auth0.com/"
        oauth_clientId: "rkGztdGvKDLDyFGyoWSXAEvuGDevwM5V"
        oauth_clientSecret: "gx-kQWiJ4x8MAA8fq1hBL01UdiNSoJsnZavdOl0x_28via7KDpgSsrkjC-zXnnJL"
        TwitterCallBackURL: "https://test.storefries.com/dashboard/content/newpost/twitter"
        chargebee_api_key: "test_xM2e2ia5BpizgyKcqISEg9CJScWLwcucU"
        Hashtag_api_key: "4e1fb16e2bmsh33a34178ff076b3p1f2af1jsn91af61c7f652"
        LinkedInClientId: "78la5qr9s8e750"
        Facebook_redirctUrl: "https://test.storefries.com/dashboard/connect/new/instagram"
        Fb_redirectUrl: "https://test.storefries.com/dashboard/connect/new/facebook"
        email_validation_check: "no"
        email_validation_url: "https://api.zerobounce.net/v2/validate?api_key="
        email_validation_api_key: "afb0b1d9ca5745c48729e512f02c4c4e"
        lifetime_plan_enable: "lifetime_plan_enable"
        LinkedInClientSecret: "C2QxygwKAaniVFbv"
        Rebrandly_key: "1144479f5e4347b68f43375f37d45670"
        locationAppId: "9e24af5e57msh04451f988199844p1b67fejsn7e1824269b53"
        recaptcha_enable: "yes"
        Twitter_ConsumerKey: "eLD1dQVA2Sz4rN166vyJnF8m8"
        LinkedInCallbackURL: "https://test.storefries.com/dashboard/connect/new/linkedin?"
        Google_redirctUrl: "https://test.storefries.com/dashboard/connect/new/youtube"
        Facebook_ClientKey: "62856eebf9511cf012f0d0be3cdec2db"
        Manage_ProfilePage: "https://test.storefries.com/dashboard/connect/new/gmb"
        Facebook_ClientId: "125112632754235"
        chargebee_site: "storefries-test"
        sender_email: "dev@aikyne.com"
        BitlyClientSecret: "db111d870bd912e6483cc99f69706f46971f8b5b"
        notification_email: "dev@aikyne.com"
        trial_enable: yes
        Google_ClientId: "781834412445-ggdcsq1tuvsvsg99uh3pg6iqc6jqi4ug.apps.googleusercontent.com"
        confirm_endPoint: "https://k2c6d61wth.execute-api.ap-south-1.amazonaws.com/Dev/aikyne/"
        BitlyRedirectURL: "https://test.storefries.com/bitlysuccess"
        s3_bucket_name: "aikyne-mediafiles"
        site_url: "https://test.storefries.com"
        aws_region: "ap-south-1"
        Google_ClientSecret: "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"
        BitlyClientId: "68e34eace85477dfb10db34f83b69e0148e105d2"
        Twitter_ConsumerSecret: "qtO5wIc479drT3YqmiNYzRSTsc6hrpVR7paj8ZgMAAoDdSW50H"
      FailOnWarnings: true

  AccessLogs:
    Type: AWS::Logs::LogGroup

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: "https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/"
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: HttpApi
